# HTTP → HTTPS
server {
    listen 80;
    server_name moodify-ai.mustafaerhanportakal.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name moodify-ai.mustafaerhanportakal.com;

    ssl_certificate /etc/letsencrypt/live/moodify-ai.mustafaerhanportakal.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/moodify-ai.mustafaerhanportakal.com/privkey.pem;

    error_page 502 503 504 /errors/502.html;
    location = /errors/502.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        proxy_pass http://moodify-ai-web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /api/ {
        proxy_pass http://moodify-ai-backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}
